version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt

artifacts:
  files:
    - '**/*'
  discard-paths: yes